import type { NotificationData } from './Notificacoes.types';

// Mock de notificações. "details" contém dados fictícios até integração com API real.
// `statusLocacao` e `locacaoId` conectam a notificação a uma locacao real de
// `mockLocacoes` (MinhasLocacoes.mock.ts), garantindo que ícone/cor sigam o mesmo
// padrão de `STATUS_CONFIG` e que os botões do modal levem à locacao correta.
export const mockNotifications: NotificationData[] = [
  {
    id: '1',
    type: 'success',
    categoria: 'locacao-confirmada',
    title: 'Locacao Confirmada',
    description: 'Sua locacao da Parafusadeira Furadeira de Impacto Hanabi foi confirmada.',
    timestamp: '04/07/2026 às 10h15',
    date: '2026-07-04T10:15:00',
    statusLocacao: 'preparandoEntrega',
    locacaoId: '3',
    details: {
      equipamento: 'Parafusadeira Furadeira de Impacto Hanabi',
      status: 'Confirmada',
      dataConfirmacao: '04/07/2026 às 10h15',
      periodoLocacao: '05/07/2026 a 07/07/2026 (2 dias)',
      valor: 'R$ 89,90',
      formaPagamento: 'Cartão de crédito •••• 4521',
    },
  },
  {
    id: '2',
    type: 'warning',
    categoria: 'devolucao-pendente',
    title: 'Devolução Pendente',
    description: 'A devolução da Serra Circular Profissional DESOON 24 Dentes deve ser feita amanhã.',
    timestamp: '03/07/2026 às 17h00',
    date: '2026-07-03T17:00:00',
    showRenovar: true,
    statusLocacao: 'aguardandoDevolucao',
    locacaoId: '6',
    details: {
      equipamento: 'Serra Circular Profissional DESOON 24 Dentes',
      status: 'Pendente',
      dataLimite: '05/07/2026 às 18h00',
    },
  },
  {
    id: '3',
    type: 'delivery',
    categoria: 'entrega-andamento',
    title: 'Entrega em Andamento',
    description: 'O Aparador De Grama Bipartido Tramontina está a caminho.',
    timestamp: '',
    date: '2026-07-04T13:00:00',
    extraInfo: 'Tempo estimado de chegada: Hoje às 15:00',
    statusLocacao: 'emTransporte',
    locacaoId: '4',
    details: {
      equipamento: 'Aparador De Grama Bipartido Tramontina',
      statusEntrega: 'Saiu para entrega',
      previsaoChegada: 'Hoje às 15:00',
    },
  },
  {
    id: '4',
    type: 'success',
    categoria: 'ferramenta-devolvida',
    title: 'Ferramenta Devolvida',
    description: 'A devolução da Serra Circular Profissional DESOON 24 Dentes foi registrada.',
    timestamp: '01/07/2026 às 09h40',
    date: '2026-07-01T09:40:00',
    statusLocacao: 'finalizada',
    locacaoId: '10',
    details: {
      equipamento: 'Serra Circular Profissional DESOON 24 Dentes',
      status: 'Devolvida sem avarias',
      dataDevolucao: '01/07/2026 às 09h40',
    },
  },
  {
    id: '5',
    type: 'warning',
    categoria: 'pagamento-pendente',
    title: 'Pagamento Pendente',
    description: 'O pagamento da locacao da Pistola de Pintura The Black Tools ainda não foi confirmado.',
    timestamp: '20/06/2026 às 14h20',
    date: '2026-06-20T14:20:00',
    showRenovar: true,
    statusLocacao: 'aguardandoPagamento',
    locacaoId: '2',
    details: {
      equipamento: 'Pistola de Pintura The Black Tools',
      statusPagamento: 'Aguardando confirmação',
      valor: 'R$ 145,00',
    },
  },
  {
    id: '6',
    type: 'error',
    categoria: 'locacao-cancelada',
    title: 'Locacao Cancelada',
    description: 'Sua locacao da Serra Circular Profissional DESOON 24 Dentes foi cancelada.',
    timestamp: '19/06/2026 às 11h05',
    date: '2026-06-19T11:05:00',
    statusLocacao: 'cancelada',
    locacaoId: '9',
    details: {
      equipamento: 'Serra Circular Profissional DESOON 24 Dentes',
      motivoCancelamento: 'Equipamento indisponível na data solicitada',
      dataCancelamento: '19/06/2026 às 11h05',
      valorReembolso: 'R$ 65,00',
    },
  },
  {
    id: '7',
    type: 'error',
    categoria: 'devolucao-atrasada',
    title: 'Devolução em Atraso',
    description: 'A devolução da Parafusadeira e Furadeira WAP 12V Cinza está atrasada.',
    timestamp: '18/06/2026 às 09h00',
    date: '2026-06-18T09:00:00',
    showRenovar: true,
    locacaoId: '7',
    details: {
      equipamento: 'Parafusadeira e Furadeira WAP 12V Cinza',
      dataLimite: '17/06/2026 às 18h00',
      diasAtraso: '1 dia',
      multa: 'R$ 15,00',
    },
  },
  {
    id: '8',
    type: 'success',
    categoria: 'entrega-concluida',
    title: 'Entrega Concluída',
    description: 'A Parafusadeira e Furadeira WAP 12V foi entregue com sucesso.',
    timestamp: '17/06/2026 às 15h20',
    date: '2026-06-17T15:20:00',
    statusLocacao: 'emAndamento',
    locacaoId: '5',
    details: {
      equipamento: 'Parafusadeira e Furadeira WAP 12V',
      dataEntrega: '17/06/2026 às 15h20',
      recebidoPor: 'Portaria do condomínio',
    },
  },
  {
    id: '9',
    type: 'success',
    categoria: 'pagamento-confirmado',
    title: 'Pagamento Confirmado',
    description: 'O pagamento da locacao da Parafusadeira Furadeira de Impacto Hanabi foi aprovado.',
    timestamp: '16/06/2026 às 10h30',
    date: '2026-06-16T10:30:00',
    statusLocacao: 'preparandoEntrega',
    locacaoId: '3',
    details: {
      valor: 'R$ 89,90',
      formaPagamento: 'Cartão de crédito •••• 4521',
      dataConfirmacao: '16/06/2026 às 10h30',
    },
  },
  {
    id: '10',
    type: 'error',
    categoria: 'pagamento-recusado',
    title: 'Pagamento Recusado',
    description: 'Não conseguimos aprovar o pagamento da sua locacao.',
    timestamp: '15/06/2026 às 08h45',
    date: '2026-06-15T08:45:00',
    statusLocacao: 'aguardandoPagamento',
    locacaoId: '2',
    details: {
      valor: 'R$ 145,00',
      formaPagamento: 'Cartão de crédito •••• 1187',
      motivoRecusa: 'Limite insuficiente',
    },
  },
  {
    id: '11',
    type: 'promotion',
    categoria: 'promocao-disponivel',
    title: 'Oferta Especial',
    description: '20% de desconto em ferramentas elétricas essa semana.',
    timestamp: '14/06/2026 às 09h00',
    date: '2026-06-14T09:00:00',
    details: {
      categoriaEquipamento: 'Ferramentas elétricas',
      cupom: 'LOCATEM20',
      desconto: '20%',
      validade: '21/06/2026',
    },
  },
  {
    id: '12',
    type: 'reminder',
    categoria: 'avaliacao-pendente',
    title: 'Avalie sua locacao',
    description: 'Conte pra gente como foi alugar a Serra Circular Profissional DESOON 24 Dentes.',
    timestamp: '13/06/2026 às 12h00',
    date: '2026-06-13T12:00:00',
    statusLocacao: 'finalizada',
    locacaoId: '10',
    details: {
      equipamento: 'Serra Circular Profissional DESOON 24 Dentes',
      dataDevolucao: '01/07/2026 às 09h40',
      notaSugerida: '5 estrelas',
    },
  },
  {
    id: '13',
    type: 'message',
    categoria: 'nova-mensagem',
    title: 'Nova Mensagem',
    description: 'Você recebeu uma mensagem do suporte Locatem.',
    timestamp: '12/06/2026 às 17h10',
    date: '2026-06-12T17:10:00',
    details: {
      remetente: 'Suporte Locatem',
      assunto: 'Sobre sua locacao',
      mensagem: 'Olá! Confirmamos que seu equipamento já está separado para devolução.',
    },
  },
];

export const PAGE_SIZE = 3;
